Countries = {
    "India" : "in",
    "United Arab Emirates" : "ae",
    "Argentina" : "ar",
    "Austria" : "at",
    "Australia" : "au",
    "Belgium" : "be",
    "Bulgaria" : "bg",
    "Brazil" : "br",
    "Canada" : "ca",
    "Switzerland" : "ch",
    "China" : "cn",
    "Colombia" : "co",
    "Cuba" : "cu",
    "Czech Republic" : "cz",
    "Germany" : "de",
    "France" : "fr",
    "United Kingdom" : "gb",
    "Greece" : "gr",
    "Hong Kong" : "hk",
    "Hungary" : "hu",
    "Indonesia" : "id",
    "Ireland" : "ie",
    "Israel" : "il",
    "Italy" : "it",
    "Japan" : "jp",
    "Korea, Republic" : "kr",
    "Lithuania" : "lt",
    "Latvia" : "lv",
    "Morocco" : "ma",
    "Mexico" : "mx",
    "Malaysia" : "my",
    "Nigeria" : "ng",
    "Netherlands" : "nl",
    "Norway" : "no",
    "New Zealand" : "nz",
    "Philippines" : "ph",
    "Poland" : "pl",
    "Portugal" : "pt",
    "Romania" : "ro",
    "Russian Federation" : "ru",
    "Saudi Arabia" : "sa",
    'Sweden' : "se",
    "Singapore" : "sg",
    "Slovenia" : "si",
    "Slovakia(Slovak Republic)" : "sk",
    "Thailand" : "th",
    "Turkey" : "tr",
    "Taiwan" : "tw",
    "Ukraine" : "ua",
    "United States" : "us"
}
